add cooksdistance delegation for LinearModel
JuliaStats/StatsModels.jl pull request #221
Opened 2021-04-05 22:42 UTC by ericqu

add cooksdistance delegation for LinearModel in GLM.jl. 
Discussed here: https://github.com/JuliaStats/GLM.jl/pull/415

2021-04-12 21:05 UTC, nalimilan approved these changes

2021-04-12 21:06 UTC, nalimilan commented on Project.toml
> +StatsBase = "0.33.5"
So long, StatsBase 0.22... :-D

2021-04-15 17:08 UTC, kleinschmidt requested changes
Looks good to me but needs a patch version bump.

2021-04-19 16:52 UTC, kleinschmidt approved these changes

2021-04-19 16:53 UTC, merged